name: VulcanWebhook
version: 1.0-SNAPSHOT
main: me.victorgamer15.vulcanwebhook.VulcanWebhook
depend: [ Vulcan ]
authors: [ VictorGamer15 ]
description: A simple addon for Vulcan to send a request to a webhook with punish data.
website: victorgamer15.ml
commands:
  vulcanwebhook: